Upload / delete automation tests
petar-kovac/porodev pull request #92
Opened 2022-07-18 08:46 UTC by PoroQa

2022-07-18 08:56 UTC, PoroQa commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/DataControlUtil.java
> +    public static String getFileIdFromFileName(String email, String pass, int fileIndexPosition) {
Method name will be changed to "getFileIdByJsonIndex" or something like that. I don't think it's a good solution to delete files like this but couldn't think of any another solution.

2022-07-18 19:03 UTC, udrakulic-htec requested changes

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/DataControlUtil.java
> +            given().relaxedHTTPSValidation()
think that this code block is duplicate and already extracted in uploadFile method

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/DataControlUtil.java
> +            given().relaxedHTTPSValidation()
This code block is already extracted in deleteFile method

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/UserDetailsGenerator.java
> +        return "{\n" +
for which request this requestBody is called?

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/test/java/api_test/files/UploadAndDeleteFile.java
> +        DataControlUtil.uploadFile(
Please add some assertion method in order to confirm that test is successfull

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/test/java/api_test/files/UploadAndDeleteFile.java
> +    public void delete_xml_file() {
Add some assertions, beside statusCode check
Each of assertion can be stored directly in test method
Please provide an additional assertions in rest of test-cases

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/src/test/resources/filePath.properties
> +FILEPATH0 = C:\\Users\\User\\Documents\\Lightshot\\Screenshot_7.png
most of these files can be part of a project, stored in java/test/resources dir

2022-07-18 19:03 UTC, udrakulic-htec commented on QA/PoroDevTest/testng.xml
> +<suite name="Suite1" verbose="1">
Please add more meaningful suite name

2022-07-19 08:38 UTC, PoroQa commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/DataControlUtil.java
> +            given().relaxedHTTPSValidation()
Good point, will be resolved

2022-07-19 08:55 UTC, PoroQa commented on QA/PoroDevTest/src/main/java/common/api_setup/api_common/UserDetailsGenerator.java
> +        return "{\n" +
To execute a Runtime project that takes two numbers as a parameter. This runtime project adds these two numbers

2022-07-20 09:30 UTC, PoroQa commented on QA/PoroDevTest/src/test/java/api_test/files/UploadAndDeleteFile.java
> +        logger.info("File is not deleted, still exists in the database, status code is 200");
Will be changed

2022-07-20 10:11 UTC, udrakulic-htec approved these changes

2022-07-20 10:11 UTC, udrakulic-htec commented on QA/PoroDevTest/src/test/java/api_test/files/UploadAndDeleteFile.java
> +        logger.info("File is not deleted, still exists in the database, status code is 200");
assertions still miss

2022-07-20 10:55 UTC, merged